#! /bin/sh

~/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Custom Configs

bspc config focus_follows_pointer true

#### BSPWM coloring ####
bspc config normal_border_color               "#45475a"
bspc config active_border_color	      	      "#1e1e1e"
bspc config focused_border_color	      "#74c7ec"


